- components/steps/style/index.css
- components/steps/style/index.less
- components/steps/style/label-placement.less
- package.json
- src/App.jsx
- src/Home/index.jsx
- src/templates/steps.jsx
- style/index.less
- styleguide.config.js
fix the steps bug ,add doc files , add slider and input-number
> F steps zb

- components/input-number/inputNumber.jsx
- package.json
- styleguide.config.js
- webpack.prod.js
fix the webpack build slow questions and error about the components.
> F webpack zb

- components/affix/index.jsx
- components/affix/readme.md
- components/breadcrumb/readme.md
- components/breadcrumb/style/index.less
- components/dropdown/style/index.less
- src/templates/affix.jsx
> F affix zb

- components/upload/readme.md
- src/templates/layout.jsx
> delete the layout.css

- components/breadcrumb/style/index.less
- components/steps/readme.md
fix the steps and breadcrumb components.
> fix the steps and breadcrumb components bug

- src/Home/index.jsx
> add the page nav item

- components/select/style/index.less
- components/tree-select/style/index.less
- src/App.jsx
- src/Home/index.jsx
- src/templates/index.jsx
- src/templates/treeSelect/BasicTreeSelect.jsx
- src/templates/treeSelect/CheckableTreeSelect.jsx
- src/templates/treeSelect/MultipleTreeSelect.jsx
- src/templates/treeSelect/ProduceData.jsx
- src/templates/treeSelect/index.jsx
- src/templates/treeSelect/maxTagTreeSelect.jsx
finish the treeSelect API and UI style.
> finish the treeSelect API and UI style

- components/breadcrumb/readme.md
- components/form/readme.md
- components/form/style/index.less
- src/templates/form/index.jsx
finish the form Api and Ui style test ,add the breadcrumb Router examples.
> F progress zb

- components/breadcrumb/style/index.less
> change the color

- components/upload/upload.jsx
> 修复上传文件列表必须配合移除回调函数才能删除的问题

- components/version/index.jsx
- components/version/style/index.less
- styleguide.config.js
- styleguide/components/link.js
> Feature update log

- components/select/style/index.less
> 修复disabled 为true 时字体颜色和背景颜色一致

- styleguide/css/main.css
> 更改组件网站首页文字字体样式

- src/templates/affix/ContainerAffix.jsx
> 修复Affix无法固定在容器顶部

- components/modal/style/modal.less
> 优化Modal组件 confirm场景下组件样式统一

- components/badge/style/index.less
- components/radio/radio.jsx
- components/radio/readme.md
- components/radio/style/index.less
- components/table/style/index.less
- src/templates/radio/BasicRadio.jsx
> Radio组件新增只读API readOnly

- components/badge/style/index.less
- components/checkbox/checkbox.jsx
- components/checkbox/checkboxGroup.jsx
- components/checkbox/readme.md
- components/checkbox/style/mixin.less
- components/table/style/index.less
- src/templates/checkbox/BasicCheckbox.jsx
- src/templates/checkbox/CombinationCheckbox.jsx
> Checkbox组件新增只读API readOnly

- components/calendar/style/index.less
- style/theme/default/compoments/calendar.less
> 修复日历组件切换日期箭头颜色

- components/tag/style/index.less
> 修复Tag组件cursor: pointer场景

- style/theme/default/compoments/steps.less
> 修复Steps未完成状态图标颜色

- components/steps/style/index.less
- components/steps/style/vertical.less
> 修复Steps组件竖直方向上样式问题

- components/dropdown/dropdown-normal.jsx
- components/dropdown/dropdown.jsx
- components/dropdown/readme.md
- components/dropdown/style/index.less
- src/templates/dropdown/BasicDropdown.jsx
> 修复Dropdown组件disabled属性

- components/steps/style/vertical.less
> 修复Steps组件竖直场景下步骤图标距离

- components/select/style/index.less
> select 统一清除icon的大小为14px

- components/button/style/index.less
- components/button/style/mixin.less
> 修复按钮在幽灵模式下图标颜色问题

- components/table/style/index.less
- components/table/table.jsx
修复table在无key的情况下选中所在行无变化同时优化嵌套子表格增加背景色区别父表格
> 修复table在无key的情况下选中所在行无变化同时优化嵌套子表格增加背景色区别父表格
